---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracledbxe-data-pv
  labels:
    app: oracledbxe
    owner: jnb
  namespace: jnb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: oracledbxe-startup-cm
  labels:
    app: oracledbxe
    owner: jnb
  namespace: jnb
data:
  setListenerLocalAccess.sql:
    execute DBMS_XDB_CONFIG.SETLISTENERLOCALACCESS(false)
---
kind: Pod
apiVersion: v1
metadata:
  name: oracledbxe
  labels:
    app: oracledbxe
    owner: jnb
  namespace: jnb
spec:
  securityContext:
    fsGroup: 54321
  containers:
    - name: oracledbxe
      image: oracle/database:18.4.0-xe
      ports:
        - containerPort: 1521
        - containerPort: 5500
      env:
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: jnb-secret
              key: password4All
      volumeMounts:
        - name: config-startup-volume
          mountPath: /opt/oracle/scripts/startup
        - name: db-data-volume
          mountPath: /opt/oracle/oradata
      securityContext:
        privileged: true
  volumes:
    - name: config-startup-volume
      configMap:
        name: oracledbxe-startup-cm
    - name: db-data-volume
      persistentVolumeClaim:
        claimName: oracledbxe-data-pv
---
kind: Service
apiVersion: v1
metadata:
  name: oracledbxe
  labels:
    app: oracledbxe
    owner: jnb
  namespace: jnb
spec:
  selector:
    app: oracledbxe
    owner: jnb
  ports:
  - port: 1521
    name: sqlnet
    targetPort: 1521
  - port: 5500
    name: em
    targetPort: 5500
