version: '3'
services:
  jnb-postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Beheer_01
    restart: always
    volumes:
      - "jnb-postgres:/var/lib/postgresql/data"
  jnb-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=Beheer_01
    restart: always
volumes:
  jnb-postgres: