version: '3.2'
services:
  jnb-wls-dev:
    image: oracle/weblogic:12.2.1.4-developer
    ports:
      - "7001:7001"
      - "9002:9002"
    restart: always
    volumes:
      - type: bind
        source: ./files
        target: /u01/oracle/properties