version: '3.8'
services:
  jnb-keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "18444:8443"
    environment:
      - KEYCLOAK_PASSWORD=Dummy_123
      - KEYCLOAK_USER=admin
      - KEYCLOAK_ALWAYS_HTTPS=true
      - KEYCLOAK_IMPORT=/opt/jboss/files/dummyrealm.json
    restart: always
    volumes:
      - type: bind
        source: ./files
        target: /opt/jboss/files
