version: '3.8'
services:
  jnb-keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "18444:8080"
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=Dummy_123
      - KEYCLOAK_ADMIN=admin
    restart: always
    command: start-dev --import-realm
    volumes:
      - type: bind
        source: ./files
        target: /opt/keycloak/data/import
