version: '3.8'
services: 
  jnb-gitlab-ee:
    image: 'gitlab/gitlab-ee:12.2.0-ee.0'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost'
        letsencrypt['enable'] = false
        gitlab_rails['initial_root_password'] = 'Dummy_123'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '18089:80'
      - '18090:443'
      - '18091:22'
    volumes:
      - jnb-gitlab-ee-config:/etc/gitlab
      - jnb-gitlab-ee-data:/var/log/gitlab
      - jnb-gitlab-ee-logs:/var/opt/gitlab
      - type: bind
        source: ../certs/server.crt
        target: /etc/gitlab/ssl/localhost.crt
      - type: bind
        source: ../certs/server.key
        target: /etc/gitlab/ssl/localhost.key
volumes: 
    jnb-gitlab-ee-config:
    jnb-gitlab-ee-data:
    jnb-gitlab-ee-logs: