version: '3.8'
services: 
    jnb-cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        environment:
            - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
            - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
        ports:
            - 18088:8081
            - 10251:10251
            - 10252:10252
            - 10253:10253
            - 10254:10254
        volumes: 
            - jnb-cosmosdb:/tmp/cosmos/appdata
volumes: 
    jnb-cosmosdb: