version: '3'
services:
  jnb-rabbitmq:
    image: rabbitmq:management
    hostname: jnb-rabbit
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Dummy_123
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - type: bind
        source: ./files
        target: /etc/rabbitmq