version: '3.2'
services:
  jnb-mongodb:
    image: mongo:4.2
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Dummy_123
    volumes:
      - jnb-mongodb:/data/db
  jnb-mongodb-express:
    image: mongo-express
    ports:
      - 18083:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=jnb-mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Dummy_123
volumes:
  jnb-mongodb: