services:
  jnb-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dummy_123
    restart: always
    volumes:
      - jnb-mssql:/var/opt/mssql
volumes: 
  jnb-mssql: