version: '3.8'
services:
    jnb-elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        environment:
            - node.name=jnb-elastic
            - cluster.name=jnb-es-docker-cluster
            - discovery.seed_hosts=
            - cluster.initial_master_nodes=jnb-elastic
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - jnb-elastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
    jnb-kibana:
        image: docker.elastic.co/kibana/kibana:7.17.0
        environment: 
            - ELASTICSEARCH_HOSTS=http://jnb-elastic:9200
        ports: 
            - 5601:5601
volumes: 
    jnb-elastic: