version: '3.2'
services:
  jnb-portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    command: [ --admin-password=$$2y$$05$$ncblH/ybgCp0koy21MfxIuZ2f59H/n3NsmSJaFuh0RDD3BI3xHy0i, '--host=unix:///var/run/docker.sock' ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jnb-portainer:/data
volumes:
  jnb-portainer: