version: '3.8'
services:
  jnb-cassandra:
    image: bitnami/cassandra:4.0
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=jnb-cassandra
      - CASSANDRA_PASSWORD=Dummy_123
      - CASSANDRA_PASSWORD_SEEDER=yes
    volumes:
      - jnb-cassandra:/bitnami
volumes:
  jnb-cassandra: