version: '3.2'
services:
  jnb-postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Dummy_123
    restart: always
    volumes:
      - "jnb-postgres:/var/lib/postgresql/data"
  jnb-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 18443:443
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=Dummy_123
      - PGADMIN_ENABLE_TLS=true
    restart: always
    volumes:
      - type: bind
        source: ./files/servers.json
        target: /pgadmin4/servers.json
      - type: bind
        source: ../certs/server.key
        target: /certs/server.key
      - type: bind
        source: ../certs/server.crt
        target: /certs/server.cert
volumes:
  jnb-postgres: