version: '3.2'
services:
  jnb-postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Dummy_123
    restart: always
    volumes:
      - "jnb-postgres:/var/lib/postgresql/data"
  jnb-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 18080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=Dummy_123
    restart: always
    volumes:
      - type: bind
        source: ./files/servers.json
        target: /pgadmin4/servers.json
volumes:
  jnb-postgres: