services:
  jnb-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - jnb-azurite-data:/data

volumes:
  jnb-azurite-data:
