version: '3.7'
services: 
    jnb-artemis:
        image: quay.io/artemiscloud/activemq-artemis-broker:latest
        user: jboss
        ports:
            - 5445:5445
            - 5672:5672
            - 8161:8161
            - 61613:61613
            - 61616:61616
        environment:
            - AMQ_USER=admin
            - AMQ_PASSWORD=Dummy_123
            - AMQ_EXTRA_ARGS=--relax-jolokia --http-host 0.0.0.0 --host 0.0.0.0
        volumes: 
            - "jnb-artemis:/home/jboss"
volumes: 
    jnb-artemis:
