services: 
    jnb-artemis:
        image: apache/activemq-artemis:latest
        user: artemis
        ports:
            - 5445:5445
            - 5672:5672
            - 8161:8161
            - 61613:61613
            - 61616:61616
        environment:
            - ARTEMIS_USER=admin
            - ARTEMIS_PASSWORD=Dummy_123
            - EXTRA_ARGS=--relax-jolokia --http-host 0.0.0.0 --host 0.0.0.0
        volumes: 
            - "jnb-artemis:/var/lib/artemis-instance"
volumes: 
    jnb-artemis:
