version: '3.8'

services:
  jnb-camunda-ee-postgres:
    image: postgres:12-alpine
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=Dummy_123
    restart: always
    volumes:
      - "jnb-camunda-ee-postgres:/var/lib/postgresql/data"
  jnb-camunda-ee-run:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:run-7.14.6
    ports: 
      - 18087:8080
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jnb-camunda-ee-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Dummy_123
    volumes:
      - ./files/default.yml:/camunda/configuration/default.yml
volumes:
  jnb-camunda-ee-postgres: